// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muadil.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Muadil.Infrastructure.Migrations
{
    [DbContext(typeof(MuadilDbContext))]
    partial class MuadilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Muadil.Domain.Entities.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tur")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Markalar");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.MuadilParfum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenzerlikPuani")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("KalicilikPuani")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MarkaId")
                        .HasColumnType("integer");

                    b.Property<int>("ParfumId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrunLinki")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParfumId");

                    b.HasIndex("MarkaId", "Kod")
                        .IsUnique();

                    b.ToTable("MuadilParfumler", t =>
                        {
                            t.HasCheckConstraint("CK_Muadil_Benzerlik", "\"BenzerlikPuani\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Muadil_Kalicilik", "\"KalicilikPuani\" BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("Muadil.Domain.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Notalar");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.Parfum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Fiyat50ml")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.Property<int>("MarkaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.ToTable("Parfumler");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.ParfumNota", b =>
                {
                    b.Property<int>("ParfumId")
                        .HasColumnType("integer");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<int>("Katman")
                        .HasColumnType("integer");

                    b.HasKey("ParfumId", "NotaId");

                    b.HasIndex("NotaId");

                    b.ToTable("ParfumNotalar");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.MuadilParfum", b =>
                {
                    b.HasOne("Muadil.Domain.Entities.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Muadil.Domain.Entities.Parfum", "Parfum")
                        .WithMany("Muadiller")
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marka");

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.Parfum", b =>
                {
                    b.HasOne("Muadil.Domain.Entities.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.ParfumNota", b =>
                {
                    b.HasOne("Muadil.Domain.Entities.Nota", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Muadil.Domain.Entities.Parfum", "Parfum")
                        .WithMany("Notalar")
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("Muadil.Domain.Entities.Parfum", b =>
                {
                    b.Navigation("Muadiller");

                    b.Navigation("Notalar");
                });
#pragma warning restore 612, 618
        }
    }
}
